- apps/docs/.eslintrc.json
warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
then caused 
`Pages directory cannot be found at . If using a custom path, please configure with the `no-html-link-for-pages` rule in your eslint config file.`
Both are fixed now
> update next config to remove the warning

- .changeset/sixty-bananas-drop.md
- apps/docs/datas/tokens-dark.json
- apps/docs/datas/tokens.json
- packages/tokens/src/tokens/core/space.tokens.json
> fix for token that was not a size

- .changeset/wicked-seahorses-flash.md
- apps/docs/datas/tokens-dark.json
- apps/docs/datas/tokens.json
- packages/tokens/package.json
- packages/tokens/src/stories/components/List.tsx
- packages/tokens/src/stories/components/list.css
- packages/tokens/src/stories/tokens.stories.ts
- packages/tokens/src/tokens/semantic/dark/dataViz.tokens.json
- packages/tokens/src/tokens/semantic/light/dataViz.tokens.json
- pnpm-lock.yaml
As discussed with both Francis, it's easier to distinguish core tokens from dataviz tokens if dataviz tokens are prefixed with dataviz. 
Also colors for test values have been split in multiple tests, with a better representation of their color
> feat: Updated DataViz Tokens to be prefixed with dataviz + Split color token tests in multiple tests

- apps/docs/components/ui/sidebar/Sidebar.tsx
- Some user's were baffled by the fact that Core Tokens were shown before Semantic, I reordered the nav to help discoverability.
> reordered nav

- packages/tokens/src/style-dictionary/config.ts
- packages/tokens/src/style-dictionary/format/css-dark-mode.ts
Problem 1: 
since multiple token had the "410" name, 
"asset" / "font" / "Inter" / "normal" / "410"
"asset" / "font" / "ABC Favorit Mono" / "normal" / "410"
there was a name clash with 410. By adding "name/cti/kebab" to the transforms, names are now unique. Since the transform after that uses the paths, and not the name, the rest works perfectly fine
Problem 2: 
Since the darkmode.css file refers to core values, it has to import those value. However, we had a mode/filter which excluded them all right after. So there was a warning telling us they were ignore. We can safely remove "mode/dark" filter, since the formatter "css/dark-mode" already filter out dark mode tokens inside it's code.
> chore: Removed warning in tokens' package build

- apps/docs/content/icons/react-icons/standalone-installation.mdx
- documentation example had a typo for the icon.
> fix for typo in withBodyStyle prop

- .changeset/tall-avocados-glow.md
- packages/components/tsup.build.ts
- packages/icons/tsup.build.ts
- packages/styled-system/tsup.build.ts
Some tools (storybook) do not support ES2020 synthax. I had a super hard time changing the tool config to accept this, so instead i'm compiling hopper in an older version
> Change build target to target es2019. 

- apps/docs/components/iconTable/IconItem.tsx
Copy pasting a React Icon was in the way as it was copying the whole component.
> modified the copied code when clicking an icon in the icon doc

- .changeset/famous-clocks-occur.md
- packages/styled-system/src/responsive/BreakpointContext.tsx
Modify breakpoint context to not throw, so component can render even if no provider has been declared
> patch: Change the breakpoint context to now throw when the provider has not been declared

- apps/docs/app/layout.css
- apps/docs/app/page.tsx
- apps/docs/content/icons/getting-started/introduction.mdx
- apps/docs/content/tokens/getting-started/introduction.mdx
- apps/docs/next.config.js
- CDN images were being processed by Next image optimizer, this is was not working as intended resulting in a missing image. I am disabling image compression for now.
- Inline code block were not standing out, this has been adressed.
- Links were underlined, while ok this resulted in a sub par experience when links were in a list. See screenshot.
- Some typo fixes and incorrect information fixes.
> Fix for CDN images - Readability fixes

- apps/docs/components/ui/table/TypographyTable.tsx
- apps/docs/content/tokens/semantic/typography.mdx
The documentation for the overline text style was returning Heading-md values. This PR fixes this, the cause was due to overline not having a size.
> Added an exception for overline to output the right values in the doc

- apps/docs/.eslintrc.json
- apps/docs/components/preview/FontWeightPreview.tsx
- apps/docs/components/ui/mdx/Mdx.tsx
- apps/docs/components/ui/table/TypographyVariantTable.tsx
- apps/docs/content/tokens/semantic/typography.mdx
- Typography semantic token documentation was not listing font-weight variations. This PR aims at fixing this. The first step being to show them in a table, in a future PR some improvment are going to be made UI wise.
> added a font-weight variation in typography documentation

- .changeset/config.json
Even tho the name of the property is scary, it's widely used by projects inside and outside workleap
> chore: add changeset settings to ignore bumping packages with peer dependencies for nothing.

- apps/docs/content/guides/css/text-crop.mdx
The documentation of Text Crop was linking to localhost.
> removed localhost from link

- packages/components/.eslintrc.json
- packages/components/src/IconList/docs/IconList.stories.tsx
- packages/components/src/Label/docs/Label.stories.tsx
- packages/components/src/Label/src/Label.tsx
- packages/components/src/Spinner/src/Spinner.tsx
- packages/components/src/Text/docs/Text.stories.tsx
- packages/components/src/Text/src/Text.tsx
- packages/components/src/buttons/docs/Button.stories.tsx
- packages/components/src/buttons/docs/ButtonGroup.stories.tsx
- packages/components/src/buttons/src/Button.tsx
- packages/components/src/utils/src/index.ts
Instead of 
```
import { isTextOnlyChildren } from "../../utils/src/isTextOnlyChildren.ts";
import { cssModule } from "../../utils/src/cssModule.ts";
import { composeClassnameRenderProps, SlotProvider } from "../../utils/index.ts";
```
Now it looks like this: 
```
import { cssModule, composeClassnameRenderProps, SlotProvider, isTextOnlyChildren, useRenderProps, useSlot } from "../../utils/index.ts";
```
instead of this: 
```
import { HopperProvider } from "../../index.ts"
import { TextContext } from "./index.ts"
```
Now it looks like this: 
```
import { HopperProvider } from "../../HopperProvider/index.ts"
import { TextContext } from "./TextContext.ts"
```
> Add custom eslint rules in components to ensure better imports synthax

- .changeset/twenty-carrots-sit.md
- .storybook/preview-head.html
- apps/docs/app/globals.css
- apps/docs/app/playground/typography/page.tsx
- apps/docs/app/playground/typography/typo.css
- packages/tokens/src/tokens/asset/fonts.tokens.json
- Replaced references to ABC Favorit and ABC Favorit Mono to a modified version that has a "standard" 8 as opposed to a vertically flipped 8.
> changed ABC Favorit / Mono font for the alternative one with a standard 8

- .changeset/shaggy-ways-complain.md
- packages/icons/src/Icon.module.css
- packages/icons/src/RichIcon.module.css
Pointer events none prevented icons to be "hoverable" this fixes the issue.
> icon now react to pointer events

- .storybook/main.ts
Modify the css-loader options to simplify the class names
By default, with the config, the classnames are like this: `GETEs8cGi4WwwvV1ooFy MUs8LC8twKwy5uAnhOWJ PafTkO4uwI6M3m4HX7JI`
With this new config, the classnames are like this: `hop-Button___GETEs hop-Button--primary___MUs8L hop-Button--md___PafTk`
> Update the css loader to simplifty the CSS modules classnames

- packages/components/package.json
- pnpm-lock.yaml
The changeset workflow commits new packages.json. Usually, updating the packages don't mess with the pnpm-lock, but having a loose version in the components was causing an issue
> chore: Fix the CI by chaging the components dependencies version on icons

- .changeset/two-tomatoes-refuse.md
- apps/docs/app/globals.css
- apps/docs/app/playground/typography/typo.css
- apps/docs/datas/tokens.json
- packages/styled-system/src/tokens/generated/lightSemanticTokens.ts
- packages/tokens/src/tokens/semantic/light/fonts.tokens.json
Since updating ABC Favorit Mono to fix the reversed 8 issue, the provided font was different enough to prevent a necessary text-crop rule fix.
> ABC Favorit Mono text crop value was not right since font update

- packages/components/src/buttons/src/Button.tsx
- packages/icons/src/createIcon.tsx
- packages/styled-system/src/index.ts
- packages/styled-system/src/utils/slot.ts
This PR introduce the slot function that is going to be used ONLY for interoperability between hopper and orbiter. Once orbiter is gone, we should remove this function. 
In Orbiter's codebase, they load slot's content using the useSlots hook.
```
const { button } = useSlots(children, useMemo(() => ({
button: {
className: "o-ui-dialog-button"
},
}), [sizeValue, disabled, loading]));
```
In Hopper, our button component should  be wrapped in the slot function.
```
const _Button = slot("button", forwardRef(Button));
```
> add the slot function in hopper

- apps/docs/app/globals.css
- apps/docs/app/rehype.css
- apps/docs/app/tokens.css
- apps/docs/app/ui/components/componentExample/ComponentPreviewWrapper.tsx
- apps/docs/app/ui/components/componentExample/componentExample.css
- apps/docs/app/ui/layout/header/header.css
- apps/docs/components/card/card.css
- apps/docs/components/code/InlineCode.tsx
- apps/docs/components/copyButton/copyButton.css
- apps/docs/components/iconButton/iconButton.css
- apps/docs/components/popover/popover.css
- apps/docs/components/pre/Pre.tsx
- apps/docs/components/pre/pre.css
- packages/components/src/buttons/docs/migration-notes.md
- Fixed tabbing issue where the copy code button was being focused even though it was not visible.
- Adjusted the code selection color.
- Fixed an issue where in some situations the focus color was not right in dark mode.
- Fixed an issue where the sidenav scroll bar would show behind the header gradient.
- Fixed an issue where you could focus on the `code` DOM element.
- Ghost cards should also feature a border as in some situations they were hard to read.
- Added the specific reason as to why the button `onClick` prop has been renamed to `onPress`.
> Feature/UI doc fixes - [DS-291]

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
Adding a shared .vscode folder so next devs save time during set up.
That means that devs that currently have a hidden .vscode folder in the repo with their own settings will have to move them to user settings to override them.
Copied from: https://github.com/gsoft-inc/wl-web-app-polyrepo-template/blob/main/.vscode/settings.json
> [DS-320] .vscode folder

- .changeset/fresh-readers-march.md
- .stylelintrc.js
- packages/components/src/ListBox/src/ListBoxItem.module.css
- packages/components/src/ListBox/src/ListBoxItem.tsx
- packages/components/src/checkbox/src/Checkbox.module.css
- packages/components/src/checkbox/src/Checkbox.tsx
- packages/components/src/checkbox/src/DecorativeCheckbox.module.css
- packages/components/src/checkbox/src/DecorativeCheckbox.tsx
- packages/components/src/checkbox/src/index.ts
- packages/components/src/radio/src/DecorativeRadio.module.css
- packages/components/src/radio/src/DecorativeRadio.tsx
- packages/components/src/radio/src/Radio.module.css
- packages/components/src/radio/src/Radio.tsx
- packages/components/src/radio/src/index.ts
- packages/components/src/utils/src/types.ts
Added DecorativeCheckbox and DecorativeRadio components that are used for visual purposes only. Such as inside a ListBoxItem when the `selectionIndicator` is set to `input`.
> Fix: [DS-312] Fixed accessibility issue with interactive elements inside listBoxItem

- apps/docs/app/home.css
Homepage component preview section was on 2 columns too soon adding an horizontal scrollbar in certain resolutions.
> changed responsive trigger for component preview

- packages/components/src/Link/docs/Link.stories.tsx
Since `navigate` needs an HopperProvider to work, the current story was forcing a light colorScheme instead of using the parent colorScheme, causing an accessibility issue according to the Storybook plugin. This was not the case, the issue was that the light theme was applied to the dark mode.
> fixed an accessibility alert due to the provider not having the right value in dark mode

- packages/components/src/Avatar/src/AnonymousAvatar.tsx
- packages/components/src/Avatar/src/Avatar.tsx
- packages/components/src/Avatar/src/DeletedAvatar.tsx
- packages/components/src/Avatar/src/RichIconAvatarImage.tsx
- packages/components/src/Avatar/tests/chromatic/AnonymousAvatar.stories.tsx
- packages/components/src/Avatar/tests/chromatic/Avatar.stories.tsx
- packages/components/src/Avatar/tests/chromatic/DeletedAvatar.stories.tsx
- packages/components/src/Avatar/tests/jest/AnonymousAvatar.test.tsx
- packages/components/src/Avatar/tests/jest/Avatar.test.tsx
- packages/components/src/Avatar/tests/jest/DeletedAvatar.test.tsx
- packages/components/src/Badge/src/Badge.tsx
- packages/components/src/Badge/src/FloatingBadge.tsx
- packages/components/src/Badge/tests/chromatic/Badge.stories.tsx
- packages/components/src/Badge/tests/jest/Badge.test.tsx
- packages/components/src/Header/src/Header.tsx
- packages/components/src/IconList/src/IconList.tsx
- packages/components/src/ListBox/src/ListBoxItemSkeleton.tsx
- packages/components/src/Spinner/src/Spinner.tsx
- packages/components/src/checkbox/src/CheckboxField.tsx
- packages/components/src/checkbox/src/CheckboxList.tsx
- packages/components/src/checkbox/tests/chromatic/CheckboxField.stories.tsx
- packages/components/src/checkbox/tests/jest/CheckboxField.test.tsx
- packages/components/src/layout/src/Content.tsx
- packages/components/src/layout/src/Footer.tsx
- packages/components/src/overlays/Popover/src/Popover.tsx
- packages/components/src/radio/src/RadioField.tsx
- packages/components/src/radio/src/RadioList.tsx
- packages/components/src/switch/src/SwitchField.tsx
- packages/components/src/switch/tests/chromatic/SwitchField.stories.tsx
- packages/components/src/utils/src/types.ts
Standardizing className, style and children Props for BaseComponentProps.
Renamed BaseComponentProps to BaseComponentDOMProps when it uses DOMProps 
When a component needs to use RenderProps instead, we should use BaseComponentRenderProps
> [DS-283] Standardizing className, style and children Props for BaseComponentProps

- .changeset/slimy-guests-move.md
- apps/docs/content/getting-started/react.mdx
- packages/components/src/index.css
- packages/components/src/index.ts
This adds these imports directly in the built `index.css` of the components package.
```css
@import url("@hopper-ui/icons/index.css");
@import url("@hopper-ui/tokens/fonts.css");
@import url("@hopper-ui/styled-system/index.css");
```
> [DS-330] Simplify import of css files for components

- .changeset/rude-buckets-speak.md
- .storybook/preview.tsx
- apps/docs/content/components/collections/Listbox.mdx
- packages/components/src/ListBox/docs/ListBox.stories.tsx
- packages/components/src/ListBox/src/ListBox.module.css
A Listbox should only accept option elements or a section, supporting Dividers as direct child of a listbox is not accessible. https://www.w3.org/WAI/ARIA/apg/patterns/listbox/
> Removed support for dividers in Listbox as this is not accessible

- .changeset/odd-laws-fetch.md
- apps/docs/datas/tokens.json
- packages/styled-system/src/tokens/generated/lightSemanticTokens.ts
- packages/styled-system/src/tokens/generated/styledSystemToTokenMappings.ts
- packages/tokens/src/tokens/semantic/light/dataViz.tokens.json
- Added `hop-dataviz-categorical-sequence-category11-hover` token.
- `hop-dataviz-categorical-sequence-category-11-hover` will be deprecated in the next major release.
> Added hop-dataviz-categorical-sequence-category11-hover token

- apps/docs/content/components/forms/CheckboxGroup.mdx
- apps/docs/examples/Preview.ts
- packages/components/src/checkbox/docs/checkboxgroup/controlled.tsx
- packages/components/src/checkbox/docs/checkboxgroup/description.tsx
- packages/components/src/checkbox/docs/checkboxgroup/disabled.tsx
- packages/components/src/checkbox/docs/checkboxgroup/invalid.tsx
- packages/components/src/checkbox/docs/checkboxgroup/nolabel.tsx
- packages/components/src/checkbox/docs/checkboxgroup/orientation.tsx
- packages/components/src/checkbox/docs/checkboxgroup/preview.tsx
- packages/components/src/checkbox/docs/checkboxgroup/readonly.tsx
- packages/components/src/checkbox/docs/checkboxgroup/size.tsx
- packages/components/src/checkbox/docs/checkboxgroup/variant.tsx
Added label to checkboxGroup preview documentation as it's more accessible this way.
> Added label examples to checkboxGroup doc previews

- apps/docs/components/tag/tag.css
- apps/docs/scripts/generateComponentData.ts
Grouping of props in the documentation props table was flaky, in some instances isDisabled was considered an accessibility prop, where in other place it was not. This PR follows RAC ways of grouping props, while making sure than an id? string is considered an accessibility prop and an id? key is considered exposed in the "default" props.
> Reorganized grouping of props to follow RAC

- .github/workflows/ci.yml
- netlify.toml
- package.json
At the moment, we are building the documentation when we want to only check if the sample apps build
We also build the samples app when building the documentation.
This will speed up the workflows
> Fix build steps

- apps/docs/app/ui/icons/iconTable/IconTable.tsx
- apps/docs/app/ui/icons/switcher/Switcher.tsx
- apps/docs/app/ui/icons/switcher/switcher.css
- apps/docs/app/ui/layout/sidebar/Sidebar.tsx
- apps/docs/app/ui/layout/sidebar/sidebar.css
> Allow filtering of icons and components

- packages/components/src/ListBox/src/ListBox.tsx
Set selectionMode to single by default instead of none
> Fix hovering of ListboxItem

- .changeset/calm-donkeys-deny.md
- apps/docs/content/components/buttons/LinkButton.mdx
- apps/docs/examples/Preview.ts
- packages/components/src/buttons/docs/linkButton/external.tsx
- packages/components/src/buttons/src/LinkButton.tsx
- packages/components/src/buttons/tests/chromatic/LinkButton.stories.tsx
Enhance the LinkButton component by adding an isExternal prop.
This update streamlines the API, allowing users to specify external links with a single, intuitive prop instead of manually setting target and rel. It aligns the LinkButton behavior with the existing implementation of Link, ensuring consistency across components in the codebase.
> Add isExternal to LinkButton

- apps/docs/app/playground/headings-link/page.tsx
- apps/docs/app/ui/components/componentExample/ComponentExample.tsx
- apps/docs/app/ui/components/componentExample/ComponentPreviewWrapper.tsx
- apps/docs/components/button/Button.tsx
- apps/docs/components/icon/assets/stackblitz.svg
- apps/docs/components/icon/index.tsx
Enhance the documentation by including a sandbox feature.
For each example, a button will be integrated that opens the corresponding sandbox. Users can copy and paste the code provided to explore or customize the examples.
Sandbox in question: https://stackblitz.com/edit/hopper-sandbox?file=src%2FComponent.tsx
> Add open in Stackblitz in the documentation

- .changeset/eight-islands-invent.md
- .changeset/tidy-mangos-hug.md
- .github/workflows/chromatic.yml
- apps/docs/content/components/application/HopperProvider.mdx
- apps/docs/content/icons/SVG-icons/icon-library.mdx
- apps/docs/content/icons/SVG-icons/rich-icon-library.mdx
- packages/components/src/HopperProvider/src/HopperProvider.tsx
- packages/components/src/Modal/src/BaseModal.tsx
- packages/components/src/index.ts
- packages/components/src/overlays/Popover/src/Popover.tsx
- packages/svg-icons/package.json
- packages/svg-icons/scripts/buildInlineIcons.ts
- packages/svg-icons/scripts/constants.ts
- packages/svg-icons/scripts/generate.ts
- packages/svg-icons/scripts/optimize.ts
- turbo.json
Here are the different steps of the svg-icons project:
**Add the SVG**
Place the SVG provided by design into the svg-icons/src folder.
**Generate optimized icons**
Run the generate-icons command. This process:
- Optimizes the SVG.
- Moves it to the src/optimized-icons folder.
- Replaces hardcoded colors with CSS variables, allowing customization.
**Build step**
Previously, there was no build step, only a copy from src/optimized-icons to dist/.
Now, an additional step has been introduced:
- The build reads files from src/optimized-icons/.
- It generates a .js file in dist/icons/inline/, exporting the inlined SVG as a string.
- It generated a index.js and index.d.ts file to export all the inline svgs
> Adding inline svgs to the svg-icons package

- .changeset/great-singers-kneel.md
- .changeset/stupid-cameras-impress.md
- packages/components/src/Image/src/Image.tsx
- packages/components/src/overlays/Popover/src/PopoverBase.tsx
- Fixed an issue where the Image component was logging a warning when the `alt` prop was provided, but empty.
- Fixed an issue where the zIndex should of been forwarded in the popover base component
> fix: Image's alt was logging an warning that was a false positive, and PopoverBase now forwards the zIndex

- .changeset/rotten-radios-exist.md
- packages/components/src/Callout/src/CompactCallout.module.css
- packages/components/src/Callout/src/CompactCallout.tsx
- packages/components/src/Callout/tests/chromatic/CompactCallout.stories.tsx
- packages/components/src/HopperProvider/src/HopperProvider.module.css
- packages/components/src/HopperProvider/src/HopperProvider.tsx
- packages/components/src/Link/src/Link.module.css
- packages/components/src/Link/src/Link.tsx
- packages/components/src/Link/tests/chromatic/Link.stories.tsx
- packages/components/src/Modal/src/Modal.tsx
- tooling/storybook-addon/withHopperProvider.tsx
- Hopper Provider now properly set the typography by default
- Compact Callout fixes: 
- min height of 48px
- fix margin that was added unnecessarily when there was a content and nothing else
- now set the content's typography to sm as expected
- Link fixes:
-  It is now possible to properly modify the fontweight or any other typography props directly on the link element
- Modal fixes:
- The size of the heading is now lg by default
> fix: Multiple Fixes

- packages/styled-system/src/tokens/tokenMappings.ts
This change refines several CSS property type definitions within tokenMappings.ts to allow for more valid CSS values. Specifically, it extends the CssBorder type, and adds 0 to the allowed values for properties such as GridAutoColumnsValue, GridAutoRowsValue, GridTemplateColumnsValue, GridTemplateRowsValue, HeightValue, etc.
- Updated the CssBorder type definition to include DataType.LineStyle. 
- Added 0 as a valid value for GridAutoColumnsValue, GridAutoRowsValue, GridTemplateColumnsValue, GridTemplateRowsValue. 
- Added additional values such as "-moz-max-content", "-moz-min-content", "-webkit-fit-content" and 0 to HeightValue.
- Added "normal" and 0 to LineHeightValue.
- Added "auto" and 0 to SimpleMarginValue and ComplexMarginValue. Added 0 to SimplePaddingValue and …
> feat: Extends CSS property types.

- .changeset/olive-tigers-tease.md
- apps/docs/content/components/content/Avatar.mdx
- apps/docs/examples/Preview.ts
- packages/components/src/avatar/docs/avatar-group/pressable.tsx
- packages/components/src/avatar/docs/migration-notes.md
- packages/components/src/avatar/docs/press.tsx
- packages/components/src/avatar/src/AnonymousAvatar.tsx
- packages/components/src/avatar/src/Avatar.module.css
- packages/components/src/avatar/src/Avatar.tsx
- packages/components/src/avatar/src/BrokenAvatar.tsx
- packages/components/src/avatar/src/DeletedAvatar.tsx
- packages/components/src/avatar/src/RichIconAvatarImage.module.css
- packages/components/src/avatar/src/RichIconAvatarImage.tsx
- packages/components/src/avatar/tests/jest/AnonymousAvatar.test.tsx
- packages/components/src/avatar/tests/jest/Avatar.test.tsx
- packages/components/src/avatar/tests/jest/BrokenAvatar.test.tsx
- packages/components/src/avatar/tests/jest/DeletedAvatar.test.tsx
- packages/components/src/spinner/docs/migration-notes.md
Enables the Avatar, AnonymousAvatar, BrokenAvatar, DeletedAvatar, and RichIconAvatarImage components to handle press events.
This change introduces the `onPress` prop, allowing developers to attach custom actions when the avatar is clicked or pressed. The Avatar component now renders as a button when the `onPress` prop is provided, enhancing interactivity.
> feat(Avatar): Adds onPress prop to Avatar components

- apps/docs/content/components/internal-parts/PopoverBase.mdx
- apps/docs/examples/Preview.ts
- packages/components/src/overlays/popover/docs/popover-base/preview.tsx
- packages/components/src/overlays/popover/src/PopoverBase.tsx
Introduces documentation for the `PopoverBase` component, an internal building block that provides core popover functionality with Hopper's styling.
Includes a basic usage example and a link to the component's props table.
> feat: Adds documentation for PopoverBase component
