apps/docs/components/Utils/ThemeProvider/ThemeSwitch/ThemeSwitch.tsx
apps/docs/package.json
pnpm-lock.yaml

Added back Radix Toggle for consistency

added radix toggle for themeSwitch

---

README.md
package.json

replaced references to Untitled to hopper

replaced references to Untitled to hopper

---

README.md
package.json
packages/tokens/package.json

Change repo address from `https://github.com/workleap/wl-hopper` to `https://github.com/gsoft-inc/hopper`.

Migrate project from GitHub organization

---

packages/tokens/src/tokens/core/elevation.tokens.json
packages/tokens/src/tokens/core/shape.tokens.json
packages/tokens/src/tokens/core/space.tokens.json
packages/tokens/src/tokens/semantic/light/elevation.tokens.json
packages/tokens/src/tokens/semantic/light/shape.tokens.json
packages/tokens/src/tokens/semantic/light/space.tokens.json

feat(tokens): add new tokens group

---

.changeset/modern-knives-sneeze.md
apps/docs/components/copyButton/copyButton.css

changed color of copy button to follow guidelines

---

.changeset/strange-laws-exercise.md
packages/tokens/src/tokens/semantic/dark/colors.tokens.json
packages/tokens/src/tokens/semantic/light/colors.tokens.json

Add new tokens and other updates

---

.changeset/brown-tigers-drum.md
packages/components/tsup.build.ts
packages/components/tsup.dev.ts
packages/icons/tsup.build.ts
packages/styled-system/tsup.build.ts
packages/styled-system/tsup.dev.ts

Update tsup configs
- we are not minifying the code anymore: https://gsoftdev.atlassian.net/wiki/spaces/Workleap/pages/3837231128/Analysis+-+Hopper+components?focusedCommentId=3854499968
- make sure every file is exported individually, and the index.js only re-export files. The index.js contained everything before. This will help tree-shaking a lot

Optimize build output

---

.changeset/twelve-llamas-flash.md
packages/components/tsconfig.json
packages/icons/package.json
packages/icons/tsconfig.json
packages/styled-system/package.json
packages/styled-system/src/StyledSystemProvider.tsx
packages/styled-system/src/responsive/BreakpointProvider.tsx
packages/styled-system/src/utils/useMediaQuery.ts
packages/styled-system/tsconfig.json
packages/svg-icons/package.json
packages/tokens/tsconfig.json
pnpm-lock.yaml
tsconfig.json

Closes https://github.com/gsoft-inc/wl-hopper/issues/146

Changed some dependencies to peers, and added flexibility to dependency versions. Fixed a warning in react18 applications

---

.changeset/shy-bobcats-accept.md
packages/styled-system/src/StyledSystemProvider.tsx

Update styledsystemprovider to accept a ref

---

apps/docs/contentlayer.config.js
apps/docs/styles/themes/rehype.css

Latest Deploy of doc did not work.

modified code related to figure

---

.github/workflows/chromatic.yml

Modify the chromatic.yml workflow to automatically comment the storybook url on the PR

Add storybook link to PR

---

.storybook/preview-head.html
.storybook/preview.tsx
CONTRIBUTING.md

- Added installation procedure in CONTRIBUTING.md
- Preload fonts in storybook
- Added fonts.css to storybook
Followed this article
https://www.chromatic.com/docs/resource-loading/#loading-custom-fonts

Add our fonts to storybook

---

.changeset-templates/icons-release.md
.changeset-templates/styled-system-release.md
.changeset-templates/svg-icons-release.md
.changeset-templates/tokens-release.md

Files that can be copied and edited so the format of our release notes are more standardized

Add new Changeset Templates

---

packages/components/package.json
packages/icons/package.json
packages/styled-system/package.json
pnpm-lock.yaml

We'll be more intentional with the versions we support

update peer dependencies versions

---

.changeset/two-ducks-rescue.md

Bumped @hopper-ui/components to a major change, added @hopper-ui/icons to major

updated changeset

---

apps/docs/content/icons/svg/rich-icon-library.mdx

Added details on how to style SVG Rich icons .

Added precisions on how to style svg-rich-icons

---

apps/docs/content/icons/svg/rich-icon-library.mdx

Added missing available variable in documentation.

added third available variable in svg-rich-icons

---

apps/docs/content/icons/svg/rich-icon-library.mdx

fix typo in variable name in documentatino

fix typo in variable name in documentation

---

apps/docs/app/tokens.css
apps/docs/app/ui/layout/header/header.css
apps/docs/app/ui/layout/mobileMenu/mobileMenu.css
apps/docs/app/ui/layout/sidebar/sidebar.css
apps/docs/app/ui/layout/subHeader/subHeader.css

[Preview](https://deploy-preview-275--wl-hopper.netlify.app/components/actions/button)

Fix problème with mobile navigation

---

apps/docs/components/packageInstallation/PackageInstallation.tsx

the command for package installation should be npm install and not npm add.

Fix npm install cmd 

---

packages/components/src/radio/src/RadioField.tsx
packages/components/src/radio/tests/chromatic/RadioGroup.stories.tsx

Fix maximum update depth

---

.github/workflows/changeset.yml
.github/workflows/chromatic.yml
.github/workflows/ci.yml

this PR fixes the problem of installing pnpm in CI

Fix error with ci pipline

---

apps/docs/.eslintrc.json
apps/docs/components/featureFlag/FeatureFlag.tsx
apps/docs/components/mdx/components.tsx
apps/docs/content/components/buttons/Button.mdx
apps/docs/context/feature/FeatureFlagProvider.tsx
apps/docs/context/feature/flags.ts

Added an example in button.mdx to define what will be displayed.
- alpha: feedback round
- rc: documentation release
- next: in next iteration

Create a feature flag component for to wrap the content

---

apps/docs/app/layout.css
apps/docs/app/ui/layout/sidebar/Sidebar.tsx
apps/docs/app/ui/layout/sidebar/sidebar.css

Revamped the sidebar to make it more clear that the content is scrollable. Made the sidebar scrollable height smaller in order to have scrollbars that don't overflow the scrollable portion.

added a scrollbar permanantly on the sidebar

---

apps/docs/app/components/layout.tsx
apps/docs/app/lib/getComponentDetails.ts
apps/docs/app/lib/getPageLinks.ts
apps/docs/app/ui/layout/sidebar/Sidebar.tsx
apps/docs/app/ui/layout/sidebar/sidebar.css
apps/docs/content/components/collections/TagGroup.mdx
apps/docs/content/components/concepts/client-side-routing.mdx
apps/docs/content/components/concepts/forms.mdx
apps/docs/content/components/concepts/slots.mdx
apps/docs/content/components/concepts/styling.mdx
apps/docs/content/components/forms/Form.mdx
apps/docs/content/components/forms/HelperMessage.mdx
apps/docs/content/components/forms/NumberInputField.mdx
apps/docs/content/components/forms/TextArea.mdx
apps/docs/content/components/icons/Icon.mdx
apps/docs/content/components/icons/IconList.mdx
apps/docs/content/components/icons/RichIcon.mdx
apps/docs/content/components/pickers/ComboBox.mdx
apps/docs/content/components/pickers/Select.mdx
apps/docs/content/components/status/Chip.mdx
apps/docs/content/getting-started/react.mdx

WIP pages are no longer visible as only a page with a status of "ready" or no status are in the sidebar.
To show a page to alpha viewers the status of the page needs to be alpha.

Hiding of wip pages

---

apps/docs/app/ui/layout/header/Header.tsx

Some typos needed to be fixed in the hub menu

fixed typos in idp menu

---

apps/docs/app/ui/components/overview/Overview.tsx
apps/docs/app/ui/components/overview/overview.css

Non ready components were showing in the overview page, this mitigates the issue.

removed non ready components in overview

---

.changeset/swift-deers-shout.md

Changeset for wrong status token (option4-text / option4-text-disabled)

changeset for ds-271

---

.changeset/smooth-roses-exercise.md
apps/docs/datas/tokens-dark.json
apps/docs/datas/tokens.json
packages/styled-system/src/tokens/generated/lightSemanticTokens.ts
packages/styled-system/src/tokens/generated/styledSystemToTokenMappings.ts
packages/tokens/src/tokens/core/space.tokens.json

Added  a new core token for 1px values.

[DS-276] - Added space-10 token (1px)

---

apps/docs/app/ui/layout/header/Header.tsx
apps/docs/app/ui/layout/sidebar/Sidebar.tsx

Fix for issue 290 where the documentation top bar would move up when the menu was opened in some situations.

fixed an issue where overflow was set to auto causing issues with the nav

---

apps/docs/components/toggleButton/toggleButton.css

Fix for appearance word not appearing (badumtss) in mobile in between 37.5rem and 48rem.

modified the css rules regarding the theme toggleButton

---

apps/docs/content/components/forms/CheckboxGroup.mdx

Fix for checkboxGroup documentation.

Changed an heading for bordered variant of checkboxGroup

---

.changeset/witty-owls-shake.md
packages/components/src/inputs/src/TextArea.module.css
packages/components/src/inputs/src/TextField.module.css

Charcount contrasting issue fix.

fixed an accessibility issue regarding charcount contrast in fields

---

.changeset/wicked-rockets-grin.md
apps/docs/datas/tokens-dark.json
packages/styled-system/src/tokens/generated/darkSemanticTokens.ts
packages/tokens/src/tokens/semantic/dark/colors.tokens.json

neutral-border-press value was wrong in dark mode

neutral-border-press token fix

---

.changeset/long-plants-live.md
packages/components/src/inputs/docs/NumberField.stories.tsx
packages/components/src/inputs/docs/numberField/sizes.tsx
packages/components/src/inputs/src/NumberField.tsx
packages/components/src/inputs/tests/chromatic/NumberField.stories.tsx

Remove placeholder from NumberField

[DS-289] Remove placeholder from NumberField

---

.changeset/heavy-bulldogs-repair.md
apps/docs/datas/tokens.json
packages/styled-system/src/tokens/generated/lightSemanticTokens.ts
packages/styled-system/src/tokens/generated/styledSystemToTokenMappings.ts
packages/tokens/src/tokens/semantic/light/dataViz.tokens.json

`--hop-dataviz-categorical-sequence-cateogry12-hover` should have been `--hop-dataviz-categorical-sequence-category12-hover`

Fixed a typo in data viz token 12

---

packages/components/src/switch/src/SwitchField.tsx
packages/components/src/switch/tests/chromatic/SwitchField.stories.tsx
packages/components/src/switch/tests/jest/SwitchField.test.tsx
packages/components/src/utils/src/types.ts

Slowly converting BaseComponentProps that extends DOMProps to RenderProps from RAC

[DS-283] Standardize className, style and children

---

apps/docs/app/layout.css
apps/docs/app/tokens.css
apps/docs/app/ui/components/componentExample/ComponentExample.tsx
apps/docs/app/ui/layout/aside/Aside.tsx
apps/docs/app/ui/layout/aside/aside.css
apps/docs/app/ui/layout/header/Header.tsx
apps/docs/app/ui/layout/sectionPopover/SectionLink.tsx
apps/docs/app/ui/layout/sectionPopover/sectionLinkArrow.css
apps/docs/app/ui/layout/sectionPopover/sectionLinkArrow.tsx
apps/docs/app/ui/layout/sectionPopover/sectionLinkArrowContext.tsx
apps/docs/app/ui/layout/sectionPopover/sectionLinkContext.tsx
apps/docs/app/ui/layout/sectionPopover/sectionPopover.css
apps/docs/app/ui/layout/sectionPopover/sectionPopover.tsx
apps/docs/app/ui/layout/sidebar/sidebar.css
apps/docs/components/collapsible/collapsible.css
apps/docs/components/overlay/overlay.css
apps/docs/components/popover/Popover.tsx
apps/docs/components/popover/popover.css
apps/docs/components/toggleButton/ToggleButton.tsx
apps/docs/components/toggleButton/toggleButton.css
apps/docs/content/components/pickers/Select.mdx
apps/docs/package.json
packages/components/package.json
packages/components/src/ListBox/src/ListBoxItem.tsx
packages/icons/package.json
pnpm-lock.yaml

- Added Scrollbar to the aside section
- Added a scrollbar to the aside mobile section
- Removed an unnecessary label on the showCode button, causing the label to show on certain resolutions 
- Slightly reworked the toggleButton to be more flexible and be the right size / hover state whether it contains text or not.
- Fixed a CSS semicolon issue.

documentation UI fixes

---

packages/components/src/ErrorMessage/src/ErrorMessage.tsx
packages/components/src/switch/src/SwitchField.tsx

Fix bad usage of useRenderProps

Fix bad usage of useRenderProps

---

.changeset/real-files-search.md
packages/components/src/ListBox/src/ListBoxItem.tsx

Added the correct aria properties to render the loading listItem accessible.

fixed loading listbox state accessibility issue

---

apps/docs/app/layout.tsx
apps/docs/app/ui/layout/header/Header.tsx
apps/docs/package.json
pnpm-lock.yaml

Adding Logrocket to the Documentation of Hopper.
Will need to add the AppId in Netlify for Prod

[DS-325] Logrocket

---

apps/docs/app/components/[...slug]/page.tsx
apps/docs/content/components/collections/Listbox.mdx
apps/docs/content/components/content/Avatar.mdx
apps/docs/content/components/content/Divider.mdx
apps/docs/content/components/content/Heading.mdx
apps/docs/content/components/content/Label.mdx
apps/docs/content/components/content/Text.mdx
apps/docs/content/components/forms/Form.mdx
apps/docs/content/components/forms/HelperMessage.mdx
apps/docs/content/components/forms/NumberField.mdx
apps/docs/content/components/forms/RemainingCharacterCount.mdx
apps/docs/content/components/overlays/Popover.mdx
apps/docs/content/components/pickers/Select.mdx
apps/docs/content/components/status/Badge.mdx
apps/docs/content/components/status/FloatingBadge.mdx

- Fixed components Github links to their source.
- The Report an issue link on each components is now more dynamic.

fixed wrong github source link - prefill component issue

---

.changeset/violet-plants-hug.md
apps/docs/content/components/pickers/Select.mdx

Fix Select

---

.changeset/rare-candles-hug.md
packages/components/src/buttons/src/ButtonGroup.module.css
packages/components/src/buttons/src/ButtonGroup.tsx

- Removed align default on ButtonGroup
- Swapped horizontal and vertical alignment CSS properties.

Fixed buttonGroup default alignments

---

apps/docs/content/components/forms/Checkbox.mdx
apps/docs/content/components/forms/CheckboxGroup.mdx

- Fixed an issue where the feature flag was not applied in the CheckboxGroup documentation.

removed guidelines showing in the nav for checkboxGroup

---

apps/docs/content/components/layout/Inline.mdx
apps/docs/content/components/layout/Stack.mdx
packages/components/src/layout/docs/inline/migration-notes.md
packages/components/src/layout/docs/stack/migration-notes.md

Added migration notes for Inline and Stack component.

added migration notes for inline and stack component

---

apps/docs/app/layout.css
apps/docs/app/lib/getComponentProps.ts
apps/docs/app/ui/components/propTable/PropTable.tsx
apps/docs/app/ui/components/propTable/PropTableRender.tsx
apps/docs/app/ui/components/propTable/propTable.css
apps/docs/app/ui/layout/wrapper/wrapper.css
apps/docs/components/code/InlineCode.tsx

- The props "table" is now responsive, clearer, and has a whole new layout, for better readibility.
- Updated the layout size to make the layout breathe more.

updated layout size / reorganized props table look

---

.changeset/early-crews-sneeze.md
packages/components/src/overlays/Popover/src/Popover.module.css

Check both Select and ComboBox examples to test.

Fix: [DS-388] Scrollbar positions is now fixed

---

.changeset/funny-lemons-warn.md
packages/components/src/buttons/src/EmbeddedButton.tsx
packages/components/src/tag/src/Tag.tsx

Handle the Orbiter variants for Tag

[DS-352] Handle the Orbiter variants for Tag

---

apps/docs/content/components/buttons/ButtonGroup.mdx
apps/docs/content/components/collections/Listbox.mdx
apps/docs/content/components/collections/TagGroup.mdx
apps/docs/content/components/forms/Checkbox.mdx
apps/docs/content/components/forms/CheckboxGroup.mdx
apps/docs/content/components/forms/Form.mdx
apps/docs/content/components/forms/SearchField.mdx
apps/docs/content/components/forms/TextArea.mdx
apps/docs/content/components/forms/TextField.mdx
apps/docs/content/components/navigation/Link.mdx
apps/docs/content/components/overlays/Popover.mdx
apps/docs/content/components/pickers/ComboBox.mdx
apps/docs/content/components/pickers/Select.mdx

Made sure composed components documentation follows the same pattern.

Unified composed components documentation

---

apps/docs/content/components/collections/Listbox.mdx
apps/docs/content/components/overlays/Popover.mdx

- Added title to props table who had more than one props table.

unified props table documentation

---

apps/docs/app/home.css
apps/docs/app/ui/layout/nav/nav.css

- Adjusted spacing for one tag
- Adjusted font weight of tag in home page

small fixes to tag - 

---

packages/components/src/overlays/Popover/docs/controlled.tsx

Useless title slot on Heading Popover

Remove title slot

---

packages/components/src/Select/docs/customValue.tsx
packages/components/src/Select/docs/selectDropdown/autoMenuWidth.tsx
packages/components/src/Select/docs/selectDropdown/avatar.tsx
packages/components/src/Select/docs/selectDropdown/count.tsx
packages/components/src/Select/docs/selectDropdown/description.tsx
packages/components/src/Select/docs/selectDropdown/endIcons.tsx
packages/components/src/Select/docs/selectDropdown/footer.tsx
packages/components/src/Select/docs/selectDropdown/icons.tsx
packages/components/src/Select/docs/selectDropdown/selectionIndicator.tsx

Fix crash on Select documentation
Need to add slot="label" as per chromatic examples

Fix crash on Select documentation

---

packages/components/src/ComboBox/docs/ComboBoxOption/loadOnScroll.tsx
packages/components/src/Select/docs/selectDropdown/loadOnScroll.tsx

Addressed inconsistencies in the documentation for features with similar functionality. This update ensures greater coherence and clarity, providing a more consistent experience for developers and users alike.

Fix documentation between combobox and selecy

---

apps/docs/content/components/content/Label.mdx
apps/docs/examples/Preview.ts
packages/components/src/typography/Label/docs/optional.tsx
packages/components/src/typography/Label/src/Label.tsx

[DS-515] Add required examples with necessityIndicator

---

apps/docs/app/lib/getComponentProps.ts
apps/docs/app/ui/components/propTable/PropTable.tsx

Prop table had double tables inside one section sometimes and repeated props. This somewhat fixes it.

Fix PropTable duplicates

---

.changeset/moody-singers-refuse.md
packages/components/src/ListBox/src/ListBoxItemSkeleton.module.css

Resolved issues with Listbox loading colors to ensure proper visibility and consistency in dark mode.

Fix ListboxItemSkeleton colors

---

.changeset/silent-guests-burn.md
apps/docs/content/components/content/Card.mdx
apps/docs/content/components/navigation/Link.mdx
apps/docs/examples/Preview.ts
packages/components/src/Link/docs/standalone.tsx
packages/components/src/Link/src/Link.module.css
packages/components/src/Link/src/Link.tsx
packages/components/src/Link/tests/chromatic/Link.stories.tsx

Add standalone variant to Link

Add standalone variant to Link

---

.changeset/calm-berries-wash.md
packages/components/src/inputs/src/Input.tsx

Add StyledComponentProps to Input

Add StyledComponentProps to Input

---

.changeset/gentle-cameras-compete.md
packages/components/src/Callout/src/Callout.module.css
packages/components/src/Modal/src/Modal.module.css
packages/components/src/overlays/Popover/src/Popover.module.css

Fix Content styling in a few components

Fix Content styling in a few components

---

.changeset/metal-pandas-jump.md
packages/components/src/Callout/src/Callout.module.css
packages/components/src/IllustratedMessage/src/IllustratedMessage.module.css
packages/components/src/Modal/src/Modal.module.css
packages/components/src/Modal/tests/chromatic/CustomModal-dark.stories.tsx
packages/components/src/Modal/tests/chromatic/CustomModal-light.stories.tsx
packages/components/src/Tabs/docs/links.tsx
packages/components/src/Tabs/tests/chromatic/Tabs.stories.tsx
packages/components/src/overlays/Popover/src/Popover.module.css
packages/components/src/typography/Heading/src/Heading.module.css
packages/components/src/typography/Heading/tests/chromatic/Heading.stories.tsx

Add offsets to make Heading appear more centered

fix: Add offsets to make Heading appear more centered

---

apps/docs/app/ui/components/heading/Heading.tsx
apps/docs/app/ui/components/heading/heading.css

Remove preview only banner from Hopper

feat(doc): Remove preview only banner from Hopper

---

.changeset/silly-steaks-bow.md
apps/docs/content/components/buttons/Button.mdx
apps/docs/content/components/overlays/Alert.mdx
apps/docs/examples/Preview.ts
packages/components/src/Alert/docs/controlled.tsx
packages/components/src/Alert/docs/migration-notes.md
packages/components/src/Alert/docs/pending.tsx
packages/components/src/Alert/src/Alert.tsx
packages/components/src/Modal/docs/controlled.tsx
packages/components/src/buttons/docs/button/pending.tsx
packages/components/src/buttons/src/Button.module.css
packages/components/src/buttons/src/Button.tsx
packages/components/src/buttons/tests/chromatic/Button.stories.tsx
packages/components/src/buttons/tests/chromatic/IconButton.stories.tsx
packages/components/src/buttons/tests/jest/Button.test.tsx

Implements a pending state for the Button and Alert components to indicate ongoing background tasks.
The Button component now features a delayed spinner to provide visual feedback after a short delay, improving the user experience. The Alert component `isLoading` prop disables buttons while pending.

feat: Adds pending state to Button and Alert

---

.changeset/fuzzy-rabbits-grin.md
packages/components/src/buttons/src/Button.tsx
packages/components/src/buttons/src/ButtonContext.ts
packages/components/src/buttons/src/ButtonGroup.tsx
packages/components/src/buttons/src/ButtonGroupContext.ts
packages/components/src/header/src/Header.tsx
packages/components/src/header/src/HeaderContext.ts
packages/components/src/image/src/Image.tsx
packages/components/src/image/src/ImageContext.ts
packages/components/src/layout/src/Content.tsx
packages/components/src/layout/src/ContentContext.ts
packages/components/src/layout/src/Footer.tsx
packages/components/src/layout/src/FooterContext.ts
packages/components/src/modal/src/Modal.module.css
packages/components/src/modal/src/Modal.tsx
packages/components/src/modal/tests/chromatic/Modal-dark.stories.tsx
packages/components/src/modal/tests/chromatic/Modal-light.stories.tsx
packages/components/src/typography/heading/src/Heading.tsx
packages/components/src/typography/heading/src/HeadingContext.ts
packages/components/src/typography/text/src/Text.tsx
packages/components/src/utils/src/ClearSlots.tsx

fix(modal): header and footer buttons fight for space, leading to overflow or early line-breaks

---

.changeset/itchy-cherries-hug.md
packages/components/src/buttons/docs/toggle-button/loading.tsx
packages/components/src/buttons/docs/toggle-button/state.tsx
packages/components/src/buttons/docs/toggle-button/variant.tsx
packages/components/src/buttons/src/ToggleButton.module.css
packages/components/src/buttons/src/ToggleButton.tsx
packages/components/src/buttons/tests/chromatic/ToggleButton.stories.tsx

Adds new variants to the ToggleButton component:
- danger
- ghost-primary
- ghost-secondary (replaced tertiary)
- ghost-danger
This expands the button's styling options to provide more flexibility.

Adds variants for ToggleButton component

---

.changeset/ten-ants-reflect.md
packages/components/src/tabs/src/Tab.tsx
packages/components/src/tabs/src/TabList.module.css

 fix: Styling of Tabs to match design

---

.changeset/modern-beds-smell.md
packages/components/src/buttons/src/Button.module.css
packages/components/src/buttons/src/ToggleButton.module.css

Updates the upsell button styles to use weaker surface colors, improving visual hierarchy and reducing prominence. This change ensures a consistent and harmonious user interface.

fix: Updates upsell button colors

---

apps/docs/ai-docs/ai-docs.config.ts
apps/docs/ai-docs/types.ts
apps/docs/ai-docs/util.ts
apps/docs/app/txt/[...path]/route.ts
apps/docs/app/ui/components/dosAndDonts/DosAndDonts.ai.tsx
apps/docs/app/ui/components/dosAndDonts/DosAndDonts.tsx
apps/docs/content/ai-templates/components-concepts.mdx
apps/docs/content/ai-templates/llms-full.mdx
apps/docs/content/ai-templates/llms.mdx
apps/docs/scripts/ai-utils/generateMarkdownFromMdx.ts
apps/docs/scripts/buildAiDocs.ts

This PR adds comprehensive LLM txt support to the Hopper documentation system, enabling AI systems to access documentation in plain text format through a dedicated  endpoint.
- **New AI docs config**: Centralized configuration system for managing multiple documentation build types
- **Template-based builds**: Support for merging multiple files with template headers
- **MDX to Markdown conversion**: Convert existing MDX documentation to plain text format
- **Flexible routing**: Configure serving paths and build options per documentation section
- : Overview page with links to all documentation sections
- : Complete documentation in a single file
- : All component documentation
- : Design tokens documentation
- : Icons documentation
- : Setup and installation guides
- **Route handler**: New …

feat(docs): add llms.txt & llms-full.txt support

---

apps/docs/ai-docs/ai-docs.config.ts
apps/docs/ai-docs/types.ts
apps/docs/ai-docs/util.ts
apps/docs/app/lib/camelCase.ts
apps/docs/app/lib/formatStyledSystemName.ts
apps/docs/app/ui/icons/switcher/Switcher.ai.tsx
apps/docs/app/ui/tokens/table/TokenTable.ai.tsx
apps/docs/app/ui/tokens/table/TokenTable.tsx
apps/docs/scripts/ai-utils/generateFilesMapping.ts
apps/docs/scripts/ai-utils/generatePropsJsonFromMdx.ts
apps/docs/scripts/ai-utils/generateTokensMaps.ts
apps/docs/scripts/buildAiDocs.ts
apps/mcp-server/package.json
apps/mcp-server/src/prompts.ts
apps/mcp-server/src/tools.ts
apps/mcp-server/src/utils/docs.ts
apps/mcp-server/src/utils/toolsInfo.ts

This PR adds comprehensive support for mapping design tokens to component prop values, making it easier to use the correct prop values when implementing components.
- **New `TokensJsonBuild` type**: Defines the structure for generating token-to-prop mappings
- **`generateTokensMaps` utility**: Transforms `tokens.json` into prop value maps with both brief (prop values only) and full (prop values + raw token values) modes
- **AI docs routes**: Added `tokens/maps/brief` and `tokens/maps/full` routes for comprehensive token mapping coverage
- **Extracted `formatStyledSystemName`**: Created reusable utility function for token name formatting
- **Simplified components**: Removed duplicate logic from `TokenTable.tsx` and `TokenTable.ai.tsx`
- **Icon documentation**: Updated icon switcher to use …

feat: add tokens map support for component props mapping

---

apps/docs/app/icons/[...slug]/page.tsx
apps/docs/app/styled-system/[...slug]/page.tsx
apps/docs/app/tokens/[...slug]/page.tsx
apps/docs/app/ui/components/heading/Heading.tsx
apps/docs/app/ui/components/heading/heading.css
apps/docs/components/ai-callout/AICallout.css
apps/docs/components/ai-callout/AICallout.tsx

feat: Add callout to MCP server in the docs
